version: '3'
services:

  vuld:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.1-enterprise
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./conf:/conf
      - neo4j_data:/data/
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    env_file:
      - .env.neo4j

volumes:
  neo4j_data:
